sudo: false
language: python

python:
- 2.7
- 3.6

matrix:
include:
  - name: "2.7 Unit Test"
    python: "2.7"
  - name: "3.6 Unit Test"
    python: "3.6"

install:
- pip install tox
- pip install -r requirements.txt

script:
- tox
